### ISSUE TITLE
i have faced errors

### ISSUE THREAD

**Issue by sehunjung** [aws-samples/aws-cloudformation-apigw-sap-idocs#1]
the message is below
An error occurred (ValidationError) when calling the CreateChangeSet operation: Stack:arn:aws:cloudformation:us-east-1:619063616954:stack/apigwsapidocadapter/12a94440-d91e-11e9-90e5-0a515b01a4a4 is in ROLLBACK_COMPLETE state and can not be updated.

An error occurred (InvalidParameterException) when calling the AdminCreateUser operation: 1 validation error detected: Value 'None' at 'userPoolId' failed to satisfy constraint: Member must satisfy regular expression pattern: [\w-]+_[0-9a-zA-Z]+

An error occurred (ResourceNotFoundException) when calling the InitiateAuth operation: User pool client None does not exist.
usage: aws [options] <command> <subcommand> [<subcommand> ...] [parameters]

**Comment by kumarrk21** [comment]
Can you delete the Cloud formation stack and recreate it? Looks like the CF stack has some errors in it and the deploy script is trying to recreate the CF stack, throwing this error. We will update this repo in the next release to CDK so that you won’t have this user experience in future. For now, delete you CF stack, fix the root cause of CF error and then recreate the stack. Thanks
